# Generated by Django 6.1.1 on 2026-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinarias/'),
        ),
    ]
