# Generated by Django 6.1.1 on 2026-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_maquinaria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarriendo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo en Faena'), ('FINALIZADO', 'Finalizado y Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratoarriendo',
            name='total_pagado',
            field=models.IntegerField(),
        ),
    ]
